<a href="https://colab.research.google.com/github/aninditha0604/DataAnalyticsMethod/blob/main/Zillow_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split

In [60]:
df = pd.read_csv('/content/zillow_data.csv') #upload data
df

#df = df.drop("State", axis=1)
#df = df.drop("RegionType", axis=1)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,31-01-2000,29-02-2000,...,31-03-2024,30-04-2024,31-05-2024,30-06-2024,31-07-2024,31-08-2024,30-09-2024,31-10-2024,30-11-2024,31-12-2024
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,245958.79850,247277.53240,...,777070.72550,782516.6015,786441.6240,787131.8015,787351.3038,789059.9619,792731.2710,7.959107e+05,7.975411e+05,7.975092e+05
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,223867.40970,224215.60430,...,978266.17400,976999.3009,978370.8499,978672.9738,981439.7243,987380.3083,995703.5300,1.002298e+06,1.007363e+06,1.010958e+06
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,103281.11490,103251.09340,...,271636.04010,272742.3157,273409.0671,273343.9397,272971.9288,272554.9379,272221.9936,2.717327e+05,2.712619e+05,2.710865e+05
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,126971.28130,126963.76360,...,294746.25110,297834.5496,299975.8348,301280.1183,302105.8296,303038.4085,303929.9145,3.044987e+05,3.052932e+05,3.062394e+05
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,97762.17787,97854.23738,...,256912.34160,257244.8311,257231.7095,256860.3081,255989.9673,255196.4387,254392.5825,2.536435e+05,2.528395e+05,2.523008e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21485,52600,30062,Hungry Horse,city,MT,MT,"Kalispell, MT",Flathead County,NaN,NaN,...,353585.29210,355648.0255,356924.6729,356946.9329,356204.2767,354850.6384,353849.6401,3.522758e+05,3.502143e+05,3.491924e+05
21486,102287,30062,Kachemak City,city,AK,AK,NaN,Kenai Peninsula Borough,NaN,NaN,...,466565.20780,469184.2886,471881.1156,472926.5775,473516.0252,474758.0463,476822.7274,4.783774e+05,4.799257e+05,4.826864e+05
21487,40102,30062,Norwood,city,IL,IL,"Peoria, IL",Peoria County,NaN,NaN,...,98690.45653,100671.4095,102003.6809,103784.5307,104812.5970,105366.0948,104530.8869,1.041867e+05,1.049306e+05,1.065718e+05
21488,44782,30062,Cove,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Chambers County,NaN,NaN,...,344270.03560,347096.6373,349380.5469,350783.2714,351431.8166,351882.3742,351898.5108,3.517564e+05,3.514992e+05,3.519272e+05
21489,32723,30062,Martin City,city,MT,MT,"Kalispell, MT",Flathead County,NaN,NaN,...,526249.72710,531265.2139,532309.5676,530494.9186,527675.2746,526472.0875,527351.7958,5.287998e+05,5.315508e+05,5.342169e+05

In [61]:
copy_df = df.copy()
copy_df.shape
copy_df.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
31-08-2024    float64
30-09-2024    float64
31-10-2024    float64
30-11-2024    float64
31-12-2024    float64
Length: 308, dtype: object

In [62]:
copy_df['RegionName'].unique() #finding unique variables in the array

array(['New York', 'Los Angeles', 'Houston', ..., 'Hungry Horse',
       'Kachemak City', 'Martin City'], dtype=object)

In [63]:
duplicates = copy_df.duplicated().sum() #finding the total duplicates in the dataset
duplicates
copy_df = copy_df.drop(columns= ['SizeRank', 'RegionID','StateName', 'RegionType', 'Metro', 'CountyName'] ) #drop unnecessary columns
copy_df

,RegionName,State,31-01-2000,29-02-2000,31-03-2000,30-04-2000,31-05-2000,30-06-2000,31-07-2000,31-08-2000,...,31-03-2024,30-04-2024,31-05-2024,30-06-2024,31-07-2024,31-08-2024,30-09-2024,31-10-2024,30-11-2024,31-12-2024
0,New York,NY,245958.79850,247277.53240,248646.30880,251208.61990,253740.75970,256405.44620,259274.04450,262005.40390,...,777070.72550,782516.6015,786441.6240,787131.8015,787351.3038,789059.9619,792731.2710,7.959107e+05,7.975411e+05,7.975092e+05
1,Los Angeles,CA,223867.40970,224215.60430,225190.77890,227148.41000,229590.06330,231965.22270,234376.87820,236864.21340,...,978266.17400,976999.3009,978370.8499,978672.9738,981439.7243,987380.3083,995703.5300,1.002298e+06,1.007363e+06,1.010958e+06
2,Houston,TX,103281.11490,103251.09340,103103.66170,103057.53370,103039.09840,103218.02040,103427.46770,103749.45440,...,271636.04010,272742.3157,273409.0671,273343.9397,272971.9288,272554.9379,272221.9936,2.717327e+05,2.712619e+05,2.710865e+05
3,Chicago,IL,126971.28130,126963.76360,127225.91110,127953.14280,128881.87500,129897.51970,130801.56950,132006.93510,...,294746.25110,297834.5496,299975.8348,301280.1183,302105.8296,303038.4085,303929.9145,3.044987e+05,3.052932e+05,3.062394e+05
4,San Antonio,TX,97762.17787,97854.23738,97926.36653,98055.95079,97616.84789,97008.70299,96345.07067,96229.41219,...,256912.34160,257244.8311,257231.7095,256860.3081,255989.9673,255196.4387,254392.5825,2.536435e+05,2.528395e+05,2.523008e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21485,Hungry Horse,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,353585.29210,355648.0255,356924.6729,356946.9329,356204.2767,354850.6384,353849.6401,3.522758e+05,3.502143e+05,3.491924e+05
21486,Kachemak City,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,466565.20780,469184.2886,471881.1156,472926.5775,473516.0252,474758.0463,476822.7274,4.783774e+05,4.799257e+05,4.826864e+05
21487,Norwood,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98690.45653,100671.4095,102003.6809,103784.5307,104812.5970,105366.0948,104530.8869,1.041867e+05,1.049306e+05,1.065718e+05
21488,Cove,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,344270.03560,347096.6373,349380.5469,350783.2714,351431.8166,351882.3742,351898.5108,3.517564e+05,3.514992e+05,3.519272e+05
21489,Martin City,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,526249.72710,531265.2139,532309.5676,530494.9186,527675.2746,526472.0875,527351.7958,5.287998e+05,5.315508e+05,5.342169e+05

In [64]:
copy_df["City"] = copy_df['RegionName'] + ' , ' + copy_df['State']
copy_df
cols = ['City'] + [col for col in copy_df.columns if col != 'City']
copy_df = copy_df[cols]
copy_df

,City,RegionName,State,31-01-2000,29-02-2000,31-03-2000,30-04-2000,31-05-2000,30-06-2000,31-07-2000,...,31-03-2024,30-04-2024,31-05-2024,30-06-2024,31-07-2024,31-08-2024,30-09-2024,31-10-2024,30-11-2024,31-12-2024
0,"New York , NY",New York,NY,245958.79850,247277.53240,248646.30880,251208.61990,253740.75970,256405.44620,259274.04450,...,777070.72550,782516.6015,786441.6240,787131.8015,787351.3038,789059.9619,792731.2710,7.959107e+05,7.975411e+05,7.975092e+05
1,"Los Angeles , CA",Los Angeles,CA,223867.40970,224215.60430,225190.77890,227148.41000,229590.06330,231965.22270,234376.87820,...,978266.17400,976999.3009,978370.8499,978672.9738,981439.7243,987380.3083,995703.5300,1.002298e+06,1.007363e+06,1.010958e+06
2,"Houston , TX",Houston,TX,103281.11490,103251.09340,103103.66170,103057.53370,103039.09840,103218.02040,103427.46770,...,271636.04010,272742.3157,273409.0671,273343.9397,272971.9288,272554.9379,272221.9936,2.717327e+05,2.712619e+05,2.710865e+05
3,"Chicago , IL",Chicago,IL,126971.28130,126963.76360,127225.91110,127953.14280,128881.87500,129897.51970,130801.56950,...,294746.25110,297834.5496,299975.8348,301280.1183,302105.8296,303038.4085,303929.9145,3.044987e+05,3.052932e+05,3.062394e+05
4,"San Antonio , TX",San Antonio,TX,97762.17787,97854.23738,97926.36653,98055.95079,97616.84789,97008.70299,96345.07067,...,256912.34160,257244.8311,257231.7095,256860.3081,255989.9673,255196.4387,254392.5825,2.536435e+05,2.528395e+05,2.523008e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21485,"Hungry Horse , MT",Hungry Horse,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,353585.29210,355648.0255,356924.6729,356946.9329,356204.2767,354850.6384,353849.6401,3.522758e+05,3.502143e+05,3.491924e+05
21486,"Kachemak City , AK",Kachemak City,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,466565.20780,469184.2886,471881.1156,472926.5775,473516.0252,474758.0463,476822.7274,4.783774e+05,4.799257e+05,4.826864e+05
21487,"Norwood , IL",Norwood,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98690.45653,100671.4095,102003.6809,103784.5307,104812.5970,105366.0948,104530.8869,1.041867e+05,1.049306e+05,1.065718e+05
21488,"Cove , TX",Cove,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,344270.03560,347096.6373,349380.5469,350783.2714,351431.8166,351882.3742,351898.5108,3.517564e+05,3.514992e+05,3.519272e+05
21489,"Martin City , MT",Martin City,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,526249.72710,531265.2139,532309.5676,530494.9186,527675.2746,526472.0875,527351.7958,5.287998e+05,5.315508e+05,5.342169e+05

In [65]:
t_data = copy_df.T #transposing data
t_data.to_csv("t_data.csv", index =False)
t_data = t_data.drop(index = t_data.index[1:3])
t_data

,0,1,2,3,4,5,6,7,8,9,...,21480,21481,21482,21483,21484,21485,21486,21487,21488,21489
City,"New York , NY","Los Angeles , CA","Houston , TX","Chicago , IL","San Antonio , TX","Philadelphia , PA","Phoenix , AZ","Las Vegas , NV","San Diego , CA","Dallas , TX",...,"Fort Howard , MD","Hoisington , KS","Vermillion , MN","Quasqueton , IA","Galesville , MD","Hungry Horse , MT","Kachemak City , AK","Norwood , IL","Cove , TX","Martin City , MT"
31-01-2000,245958.7985,223867.4097,103281.1149,126971.2813,97762.17787,58059.00491,116897.0462,159622.8745,240789.1872,94955.02731,...,NaN,NaN,NaN,NaN,233241.0089,NaN,NaN,NaN,NaN,NaN
29-02-2000,247277.5324,224215.6043,103251.0934,126963.7636,97854.23738,58172.00828,117187.7157,159586.3981,241893.5146,95001.48655,...,NaN,NaN,NaN,NaN,233239.7006,NaN,NaN,NaN,NaN,NaN
31-03-2000,248646.3088,225190.7789,103103.6617,127225.9111,97926.36653,58289.76611,117554.4223,159846.3236,243142.0339,95034.06314,...,NaN,NaN,NaN,NaN,233674.8446,NaN,NaN,NaN,NaN,NaN
30-04-2000,251208.6199,227148.41,103057.5337,127953.1428,98055.95079,58542.87775,118335.4995,160451.8158,245982.4646,95145.35351,...,NaN,NaN,NaN,NaN,235640.2129,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31-08-2024,789059.9619,987380.3083,272554.9379,303038.4085,255196.4387,211242.683,427185.9818,441912.8274,1134731.245,321227.6065,...,316661.1314,83025.82365,310561.4716,138900.6521,626187.5803,354850.6384,474758.0463,105366.0948,351882.3742,526472.0875
30-09-2024,792731.271,995703.53,272221.9936,303929.9145,254392.5825,211594.254,425972.221,443591.7337,1134577.001,320437.7719,...,318484.7375,83048.0008,311344.4239,139332.2658,627089.5941,353849.6401,476822.7274,104530.8869,351898.5108,527351.7958
31-10-2024,795910.7288,1002297.706,271732.6709,304498.7087,253643.4819,212069.4263,424827.572,445073.0844,1133101.997,319988.1562,...,320521.8512,82962.24861,313141.7577,140405.5712,629890.5712,352275.7654,478377.4344,104186.6579,351756.3635,528799.7881
30-11-2024,797541.0823,1007363.079,271261.8717,305293.1617,252839.5052,212624.7606,423868.6939,446495.1473,1131732.085,319472.6847,...,322662.3974,82741.36474,315920.7552,141674.1845,634220.003,350214.2837,479925.6625,104930.5833,351499.1895,531550.8111
31-12-2024,797509.1587,1010957.678,271086.5478,306239.4029,252300.7803,213608.1653,423305.9441,448071.2633,1130316.269,319020.0922,...,325151.4552,82823.78093,319568.313,143193.2512,635465.4258,349192.3942,482686.3951,106571.8466,351927.2273,534216.883

In [66]:
t_data.dtypes

0        object
1        object
2        object
3        object
4        object
          ...
21485    object
21486    object
21487    object
21488    object
21489    object
Length: 21490, dtype: object

In [67]:
t_data.isnull().sum()

0          0
1          0
2          0
3          0
4          0
        ...
21485    156
21486     62
21487    180
21488    265
21489    156
Length: 21490, dtype: int64

In [68]:
t_data.columns = t_data.iloc[0] #set first row as column header
#t_data
t_data = t_data.drop(index= t_data.index[0:1])
t_data

City,"New York , NY","Los Angeles , CA","Houston , TX","Chicago , IL","San Antonio , TX","Philadelphia , PA","Phoenix , AZ","Las Vegas , NV","San Diego , CA","Dallas , TX",...,"Fort Howard , MD","Hoisington , KS","Vermillion , MN","Quasqueton , IA","Galesville , MD","Hungry Horse , MT","Kachemak City , AK","Norwood , IL","Cove , TX","Martin City , MT"
31-01-2000,245958.7985,223867.4097,103281.1149,126971.2813,97762.17787,58059.00491,116897.0462,159622.8745,240789.1872,94955.02731,...,NaN,NaN,NaN,NaN,233241.0089,NaN,NaN,NaN,NaN,NaN
29-02-2000,247277.5324,224215.6043,103251.0934,126963.7636,97854.23738,58172.00828,117187.7157,159586.3981,241893.5146,95001.48655,...,NaN,NaN,NaN,NaN,233239.7006,NaN,NaN,NaN,NaN,NaN
31-03-2000,248646.3088,225190.7789,103103.6617,127225.9111,97926.36653,58289.76611,117554.4223,159846.3236,243142.0339,95034.06314,...,NaN,NaN,NaN,NaN,233674.8446,NaN,NaN,NaN,NaN,NaN
30-04-2000,251208.6199,227148.41,103057.5337,127953.1428,98055.95079,58542.87775,118335.4995,160451.8158,245982.4646,95145.35351,...,NaN,NaN,NaN,NaN,235640.2129,NaN,NaN,NaN,NaN,NaN
31-05-2000,253740.7597,229590.0633,103039.0984,128881.875,97616.84789,58928.60082,119199.5238,161259.3589,248973.5663,95332.17543,...,NaN,NaN,NaN,NaN,237795.194,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31-08-2024,789059.9619,987380.3083,272554.9379,303038.4085,255196.4387,211242.683,427185.9818,441912.8274,1134731.245,321227.6065,...,316661.1314,83025.82365,310561.4716,138900.6521,626187.5803,354850.6384,474758.0463,105366.0948,351882.3742,526472.0875
30-09-2024,792731.271,995703.53,272221.9936,303929.9145,254392.5825,211594.254,425972.221,443591.7337,1134577.001,320437.7719,...,318484.7375,83048.0008,311344.4239,139332.2658,627089.5941,353849.6401,476822.7274,104530.8869,351898.5108,527351.7958
31-10-2024,795910.7288,1002297.706,271732.6709,304498.7087,253643.4819,212069.4263,424827.572,445073.0844,1133101.997,319988.1562,...,320521.8512,82962.24861,313141.7577,140405.5712,629890.5712,352275.7654,478377.4344,104186.6579,351756.3635,528799.7881
30-11-2024,797541.0823,1007363.079,271261.8717,305293.1617,252839.5052,212624.7606,423868.6939,446495.1473,1131732.085,319472.6847,...,322662.3974,82741.36474,315920.7552,141674.1845,634220.003,350214.2837,479925.6625,104930.5833,351499.1895,531550.8111
31-12-2024,797509.1587,1010957.678,271086.5478,306239.4029,252300.7803,213608.1653,423305.9441,448071.2633,1130316.269,319020.0922,...,325151.4552,82823.78093,319568.313,143193.2512,635465.4258,349192.3942,482686.3951,106571.8466,351927.2273,534216.883

In [69]:
t_data = t_data.reset_index()
t_data

City,index,"New York , NY","Los Angeles , CA","Houston , TX","Chicago , IL","San Antonio , TX","Philadelphia , PA","Phoenix , AZ","Las Vegas , NV","San Diego , CA",...,"Fort Howard , MD","Hoisington , KS","Vermillion , MN","Quasqueton , IA","Galesville , MD","Hungry Horse , MT","Kachemak City , AK","Norwood , IL","Cove , TX","Martin City , MT"
0,31-01-2000,245958.7985,223867.4097,103281.1149,126971.2813,97762.17787,58059.00491,116897.0462,159622.8745,240789.1872,...,NaN,NaN,NaN,NaN,233241.0089,NaN,NaN,NaN,NaN,NaN
1,29-02-2000,247277.5324,224215.6043,103251.0934,126963.7636,97854.23738,58172.00828,117187.7157,159586.3981,241893.5146,...,NaN,NaN,NaN,NaN,233239.7006,NaN,NaN,NaN,NaN,NaN
2,31-03-2000,248646.3088,225190.7789,103103.6617,127225.9111,97926.36653,58289.76611,117554.4223,159846.3236,243142.0339,...,NaN,NaN,NaN,NaN,233674.8446,NaN,NaN,NaN,NaN,NaN
3,30-04-2000,251208.6199,227148.41,103057.5337,127953.1428,98055.95079,58542.87775,118335.4995,160451.8158,245982.4646,...,NaN,NaN,NaN,NaN,235640.2129,NaN,NaN,NaN,NaN,NaN
4,31-05-2000,253740.7597,229590.0633,103039.0984,128881.875,97616.84789,58928.60082,119199.5238,161259.3589,248973.5663,...,NaN,NaN,NaN,NaN,237795.194,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,31-08-2024,789059.9619,987380.3083,272554.9379,303038.4085,255196.4387,211242.683,427185.9818,441912.8274,1134731.245,...,316661.1314,83025.82365,310561.4716,138900.6521,626187.5803,354850.6384,474758.0463,105366.0948,351882.3742,526472.0875
296,30-09-2024,792731.271,995703.53,272221.9936,303929.9145,254392.5825,211594.254,425972.221,443591.7337,1134577.001,...,318484.7375,83048.0008,311344.4239,139332.2658,627089.5941,353849.6401,476822.7274,104530.8869,351898.5108,527351.7958
297,31-10-2024,795910.7288,1002297.706,271732.6709,304498.7087,253643.4819,212069.4263,424827.572,445073.0844,1133101.997,...,320521.8512,82962.24861,313141.7577,140405.5712,629890.5712,352275.7654,478377.4344,104186.6579,351756.3635,528799.7881
298,30-11-2024,797541.0823,1007363.079,271261.8717,305293.1617,252839.5052,212624.7606,423868.6939,446495.1473,1131732.085,...,322662.3974,82741.36474,315920.7552,141674.1845,634220.003,350214.2837,479925.6625,104930.5833,351499.1895,531550.8111
299,31-12-2024,797509.1587,1010957.678,271086.5478,306239.4029,252300.7803,213608.1653,423305.9441,448071.2633,1130316.269,...,325151.4552,82823.78093,319568.313,143193.2512,635465.4258,349192.3942,482686.3951,106571.8466,351927.2273,534216.883

In [70]:
t_data.rename(columns = {'index' : 'Date'}, inplace=True)
t_data

City,Date,"New York , NY","Los Angeles , CA","Houston , TX","Chicago , IL","San Antonio , TX","Philadelphia , PA","Phoenix , AZ","Las Vegas , NV","San Diego , CA",...,"Fort Howard , MD","Hoisington , KS","Vermillion , MN","Quasqueton , IA","Galesville , MD","Hungry Horse , MT","Kachemak City , AK","Norwood , IL","Cove , TX","Martin City , MT"
0,31-01-2000,245958.7985,223867.4097,103281.1149,126971.2813,97762.17787,58059.00491,116897.0462,159622.8745,240789.1872,...,NaN,NaN,NaN,NaN,233241.0089,NaN,NaN,NaN,NaN,NaN
1,29-02-2000,247277.5324,224215.6043,103251.0934,126963.7636,97854.23738,58172.00828,117187.7157,159586.3981,241893.5146,...,NaN,NaN,NaN,NaN,233239.7006,NaN,NaN,NaN,NaN,NaN
2,31-03-2000,248646.3088,225190.7789,103103.6617,127225.9111,97926.36653,58289.76611,117554.4223,159846.3236,243142.0339,...,NaN,NaN,NaN,NaN,233674.8446,NaN,NaN,NaN,NaN,NaN
3,30-04-2000,251208.6199,227148.41,103057.5337,127953.1428,98055.95079,58542.87775,118335.4995,160451.8158,245982.4646,...,NaN,NaN,NaN,NaN,235640.2129,NaN,NaN,NaN,NaN,NaN
4,31-05-2000,253740.7597,229590.0633,103039.0984,128881.875,97616.84789,58928.60082,119199.5238,161259.3589,248973.5663,...,NaN,NaN,NaN,NaN,237795.194,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,31-08-2024,789059.9619,987380.3083,272554.9379,303038.4085,255196.4387,211242.683,427185.9818,441912.8274,1134731.245,...,316661.1314,83025.82365,310561.4716,138900.6521,626187.5803,354850.6384,474758.0463,105366.0948,351882.3742,526472.0875
296,30-09-2024,792731.271,995703.53,272221.9936,303929.9145,254392.5825,211594.254,425972.221,443591.7337,1134577.001,...,318484.7375,83048.0008,311344.4239,139332.2658,627089.5941,353849.6401,476822.7274,104530.8869,351898.5108,527351.7958
297,31-10-2024,795910.7288,1002297.706,271732.6709,304498.7087,253643.4819,212069.4263,424827.572,445073.0844,1133101.997,...,320521.8512,82962.24861,313141.7577,140405.5712,629890.5712,352275.7654,478377.4344,104186.6579,351756.3635,528799.7881
298,30-11-2024,797541.0823,1007363.079,271261.8717,305293.1617,252839.5052,212624.7606,423868.6939,446495.1473,1131732.085,...,322662.3974,82741.36474,315920.7552,141674.1845,634220.003,350214.2837,479925.6625,104930.5833,351499.1895,531550.8111
299,31-12-2024,797509.1587,1010957.678,271086.5478,306239.4029,252300.7803,213608.1653,423305.9441,448071.2633,1130316.269,...,325151.4552,82823.78093,319568.313,143193.2512,635465.4258,349192.3942,482686.3951,106571.8466,351927.2273,534216.883

In [71]:
t_city = t_data[['Date', 'New York , NY']]
t_city

City        Date New York , NY
0     31-01-2000   245958.7985
1     29-02-2000   247277.5324
2     31-03-2000   248646.3088
3     30-04-2000   251208.6199
4     31-05-2000   253740.7597
..           ...           ...
295   31-08-2024   789059.9619
296   30-09-2024    792731.271
297   31-10-2024   795910.7288
298   30-11-2024   797541.0823
299   31-12-2024   797509.1587

[300 rows x 2 columns]

In [72]:
t_city['New York , NY'] = t_city['New York , NY'].astype(float)

<ipython-input-72-980f4fce2130>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_city['New York , NY'] = t_city['New York , NY'].astype(float)

In [73]:
t_city.dtypes

City
Date              object
New York , NY    float64
dtype: object

In [74]:
#Convert to datetime
t_city['Date'] = pd.to_datetime(t_city['Date'])
t_city

<ipython-input-74-e30d7198cb36>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  t_city['Date'] = pd.to_datetime(t_city['Date'])
<ipython-input-74-e30d7198cb36>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_city['Date'] = pd.to_datetime(t_city['Date'])

City       Date  New York , NY
0    2000-01-31    245958.7985
1    2000-02-29    247277.5324
2    2000-03-31    248646.3088
3    2000-04-30    251208.6199
4    2000-05-31    253740.7597
..          ...            ...
295  2024-08-31    789059.9619
296  2024-09-30    792731.2710
297  2024-10-31    795910.7288
298  2024-11-30    797541.0823
299  2024-12-31    797509.1587

[300 rows x 2 columns]

In [75]:
t_city.fillna(t_city.mean(numeric_only= True))
t_city

City       Date  New York , NY
0    2000-01-31    245958.7985
1    2000-02-29    247277.5324
2    2000-03-31    248646.3088
3    2000-04-30    251208.6199
4    2000-05-31    253740.7597
..          ...            ...
295  2024-08-31    789059.9619
296  2024-09-30    792731.2710
297  2024-10-31    795910.7288
298  2024-11-30    797541.0823
299  2024-12-31    797509.1587

[300 rows x 2 columns]

In [76]:
t_city.dtypes

City
Date             datetime64[ns]
New York , NY           float64
dtype: object

In [84]:

#Create the line plot
plt.figure(figsize=(12, 6)) #creates placeholder for any chart or line chart
plt.plot(t_city['Date'], t_city['New York, NY'], label = 'New York Housing Prices') #you want to plot between date and newyork column and want to label it ny housing prices
plt.xlabel('Date')
plt.ylabel('Housing Prices')
plt.title('New York Housing Prices Over Time')
plt.legend()
plt.grid()
plt.show()

TypeError: 'module' object is not callable

In [78]:
t_city['Year'] = t_city['Date'].dt.year
t_city['Month'] = t_city['Date'].dt.month
t_city['Month_Year'] = t_city['Year'] * 100 + t_city['Month']

print(t_city.head())

City       Date  New York , NY  Year  Month  Month_Year
0    2000-01-31    245958.7985  2000      1      200001
1    2000-02-29    247277.5324  2000      2      200002
2    2000-03-31    248646.3088  2000      3      200003
3    2000-04-30    251208.6199  2000      4      200004
4    2000-05-31    253740.7597  2000      5      200005

<ipython-input-78-1ad6e077dc8f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_city['Year'] = t_city['Date'].dt.year
<ipython-input-78-1ad6e077dc8f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_city['Month'] = t_city['Date'].dt.month
<ipython-input-78-1ad6e077dc8f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_city['Month_Year'] = t_city['Year'] * 100 + t_city['Month']

In [86]:
#Define features and target
#Define Features (X)
X = t_city[['Month_Year']]
y = t_city[['New York , NY']]

#Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

#fit to the Linear Regression Model
pricepredictor = LinearRegression()
pricepredictor.fit(X_train, y_train)

LinearRegression()